version: "1.0"

services:
  client:
    build: ./Client
    ports:
      - "80:80"
    depends_on:
      - server
  server:
    build: ./Server
    ports:
      - "4292:4292"
  webnsockets:
    build: ./websockets
    ports:
      - "3000:3000"
    